---
# tasks file for ansible-role-molecule
- name: Test ping
  ansible.builtin.ping:

- name: Print distribution and version of image
  ansible.builtin.debug:
    var: ansible_distribution + ansible_distribution_version

- name: Include tasks for CentOS
  ansible.builtin.include_tasks: centos.yml
  when: ansible_distribution == "CentOS"

- name: Include tasks for Debian
  ansible.builtin.include_tasks: debian.yml
  when: ansible_distribution == "Debian"

- name: Include tasks for Ubuntu
  ansible.builtin.include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
