---
name: Molecule Test
on: 
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.8
          - 3.9
          - 3.10
        ansible-version:
          - 2.11.12
          - 2.12.10
          - 2.13.5
          - 2.14.0rc1
        exclude:
          - python-version: 3.8
            ansible-version: 2.14.0rc1

    steps:
      - uses: actions/checkout@v3
        with:
          path: ansible-role-molecule

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install ansible-core==${{ matrix.ansible-version }}
          pip install -r requirements.txt
          ansible --version
          molecule --version
        working-directory: ansible-role-molecule

      - name: Test with molecule
        run: molecule test
        working-directory: ansible-role-molecule
